### ISSUE TITLE
Feature request: free positioning

### ISSUE THREAD

**Issue by ghost** [perfect-things/perfect-home#1]
Free on-page placement (like one item top-left, another bottom-right, and a pure void between). 
If I can't get it with custom css(?). 
Pleasant design, BTW.
Thanks.

**Comment by tborychowski** [comment]
Thank  you :-)

For positioning - I don't believe this is a very common use case (even personally I haven't seen anything that would work like that).

However, this is very easy to achieve with custom css. You'd  just need to do that manually, for every bookmark that you'd want to  be positioned like that.
So:
1. You need to get the css class for the bookmark.
   - open dev-tools and inspect the tile (it should be an Anchor tag with classes like `item item-bookmark item-BOOKMARK_ID`)
   - you want the class name that contains the firefox bookmark ID, e.g. `item-HNMi-AwJH2Mp`
2. Then, you add custom css for that class name, e.g.:
```css
.item-HNMi-AwJH2Mp {
   position: absolute;
   width: 170px;
   height: 160px;
   top: 10px;
   left: 10px;
}
```
And you're done! 

Let me know if you need a more detailed explanation and if that's an acceptable solution to your issue.
