### ISSUE TITLE
[docked-folder] when bookmark title is very long, the docked folder will overflow to the outside of the screen

### ISSUE THREAD

**Issue by tborychowski** [perfect-things/perfect-home#114]
If the bookmark title is very long, the docked folder will overflow on the far right. 
add 
```css
 .folder { overflow: hidden; }
```
