### ISSUE TITLE
Two backgrounds

### ISSUE THREAD

**Issue by e1a6** [perfect-things/perfect-home#119]
Hi,
 Thank you for making this addon.
I was looking for something simple that allowed to make dials in a start page out of bookmarks and it does a really good job at it.

I'm trying to customize the look using the custom css (i'm a begginer, i try to find the cod ei need by looking up at tutorials. )

I wanted to remove the title so i've used: header .title {display: none;}

The title is gone but it looks like there's another page displaying the title loading just before the one that was changed.
(It's the same with the background color).

Could you please tell me if there is way to make only the page displaying my bookmark dials to load?

**Comment by tborychowski** [comment]
Hi @e1a6,

Thanks for the feedback.

You're right on both things: the title flashes quickly with "Bookmarks menu" and background colour is set to `#333` initially.
These are so called "known bugs" :-)
Meaning that I'm aware of them and they are not easily fixable.

Ideally all assets (including custom CSS) should be loaded instantly before rendering, but the browser loads assets as follows:
1. Loads index.html first (and all inline css & js)
2. starts rendering html & css, while loading external js & css
3. processes the js
4. js loads custom css from browser storage
5. browser applies the custom css


So, the only way to not see the flashes would be if I stop rendering until all resources are loaded (and js is processed).
But before this happens - the window has to have some colour anyway.
Leaving browser's default (white), IMO, is a bad choice, because dark-theme lovers (like me) would see the eye-burning flash of white in the middle of the night :-)
If it's set to a dark colour - and someone prefers white - it won't hurt them.
So I don't think I can do much here (unless you have some ideas).

As for the title flash - "Bookmarks Menu" is the default folder selected (that should be present in every firefox) and before the javascript loads your stored settings - it displays the default first.

But I can play around with the timings and see if I can make it better :-)

**Comment by e1a6** [comment]
Thank you for your responsiveness and detailed response.

I'm don't have the expertise or knowledge in that field to be able to fully understand the issue and give you ideas that would solve the problem.

I'm a dark theme lover myself and i used to even use extensions that rendered all webpages dark so i know exacly what you mean by being hurt by "the eye-burning flash of white in the middle of the night". I had to switch back to black fonts on white pages even though it's tiring for the eyes it's easier for me to read (and i guess this is why it's most of the time what web pages use as default). 

You should consider that a significant part of the people using your addon will use the white theme you have provided to go with the white theme that defaults in their browsers and browsing experience so if possible at some point of course  you should give an option to be able to chose the color to match the theme used.  ( i understand the limitations due to the fact that firefox has been remade from scratch recently and give less access to developpers for security reasons).

You can see [here](https://i.postimg.cc/jSqKN5XD/title1.gif) that the title is in one line in the first page then in two lines probably because of the language?

This is[ what i'm trying to replicate](https://i.postimg.cc/3wZCsB6w/3.png) in Firefox. It's the extension humble new tab for chromium browsers. It also exists  in Firefox but it can't retrieve favicons for some websites and doesn't give the option the chose custom images like yours. I thought maybe you could find an answer  to the issue there in the code as the addons provide the same kinfd of service. (Just throwing  ideas sorry if it's something that you alreadu thought of or not helpful)

In anycase i'm really gratefull that you shared your great work  ans made it availaible for everyone!

**Comment by tborychowski** [comment]
Hi again,

So I see 3 main items in your post so let's separate them:

# 1. default background
As I mentioned before - it's impossible to load the user preferences before the page starts rendering (as the settings are stored in the browser only. However, I started thinking and came up with a better idea (than there is currently): css can now detect the OS settings (using media-queries) so I can set white background for users who prefer light, and so on 👍 

# 2. Regarding the long title
the title element should have the full width of the page (almost), so this should not be wrapped, unless:
- you applied some custom css that does that
- your title contains (an invisible) line break

Could you try go to the Firefox bookmark's editor, edit the title that wraps by removing the whole text and re-entering it manually? (and see if that changes anything?)

# 3. Layout
You could use the docked folders for that and just customize the css, e.g.:
- First - add the bookmarks from your columns to separate folders (so that each column is a separate folder)
- then - add these folders as "Docked folders" in Settings
- lastly - paste the css below into the "Custom CSS" box.

There are 2 ways of doing that (so paste one or the other):
1. using favicons 
You won't have to manually select images for thumbnails, but if the icons are bigger than 16x16px they will look ugly). I added comments so you can see what's happening (you can remove them if you don't need them:
```css
/* hide the main folder altogether */
#app main { display: none; }

/* move docked folders to the center */
.folders { position: relative; justify-content: center; }
.folders .folder-header { display: none; }

/* show the items in them by default */
.folder-items.hidden { opacity: 1; visibility: visible; }
/* show height to depend on the content */
.folder-items { max-height: unset; }

/* remove borders & padding */
.folder { border: none; padding: 0; }

/* hide things we don't need */
.folder .folder-title,
.folder .item-title,
.item-thumb-suffix { display: none; }

/* make the favicon bigger */
.folder .item-favicon { width: 40px; height: 40px; background-color: transparent; }
```

2. Using thumbnails 
You can select any image for thumbnail and they will look better, but need to do it manually:
```css
/* hide the main folder altogether */
#app main { display: none; }

/* move docked folders to the center */
.folders { position: relative; justify-content: center; }
.folders .folder-header { display: none; }

/* show the items in them by default */
.folder-items.hidden { opacity: 1; visibility: visible; }
/* show height to depend on the content */
.folder-items { max-height: unset; }

/* remove borders & padding */
.folder { border: none; padding: 0; }

/* hide things we don't need */
.folder .folder-title,
.folder .item-title,
.folder .item-favicon,
.item-thumb-suffix { display: none; }

/* show the thumbnails */
.folder .item-thumb { width: 64px; height: 64px; display: block; }
```

This is how it looks at mine:
<img width="1538" alt="Screenshot 2020-11-23 at 14 16 13" src="https://user-images.githubusercontent.com/392513/99972523-884ca200-2d96-11eb-91c4-460020d8ca2f.png">

**Comment by e1a6** [comment]
Hi,


Thank you! Your explanation was super clear.

I applied the css for the second option (to manually change the thumbnails) because i have bookmaks for sites requiring login so firefox can't retrievethe favicon for those at the moment.(from what i've understood)

[Here](https://i.postimg.cc/RFHWTjZ6/title2.gif)'s what it looks like for now (i didn't have the time yet to change the thumnails).

There are a few things that might need some changing in the css. It looks like the folders titles still appear in the background.

Is there something i forgot or didn't do right?

[White version](https://i.postimg.cc/13zRRLwx/title3.gif)


The title issue completly disapeared as soon as i put your css code in the custom css field. 

Ps: your home page set up looks great!)

**Comment by tborychowski** [comment]
Hi again,

So: Docked folders are a bit different: they don't display nested folders (so unfortunately you'll loose the nesting).
As for the issue that I think happens for you is that there's a horizontal scrollbar showing in columns.
You can disable it with css, by adding this line:
```css
.folder .folders { overflow: hidden; }
```

But, the reason the scrollbars show up is this: when a thumbnail has not been set - it defaults to a text-based thumbnail (usually a domain/host name) and - if should fit into the box but with custom CSS that may not work correctly, so - if the text is long - it just overflows the thumbnail box.
So - the short story is - once you set the thumbnails for all items in the column - the scrollbars should not show up :-)
