### ISSUE TITLE
Site screenshots instead of/along with thumbnails

### ISSUE THREAD

**Issue by h45h3ncryp73d** [perfect-things/perfect-home#122]
I was a long time FVD Speed Dial user and really got used to it so I've abandoned bookmarking pages a long time ago. Now I feel like getting back to it to be able to sync them through my private cloud and not some "cryptic" service(s). In my search I stumbled upon your addon and I must say I really like it a lot.
What I'd like to ask is if it would be possible for you to implement taking bookmarks' screenshots and using them instead of thumbnails. At least for me it is easier to navigate based on site screenshots ...

Thanks.

**Comment by tborychowski** [comment]
Hi,
Thanks for the feedback and the kind words. All the more sorry I feel to say that:

Short answer is: no.

Longer answer is: it requires a free and reliable service that would take these screenshots for all bookmarks of all of the extension users, as firefox does not provide that and creating them from the extension would be terrible. And such a thing doesn't exist.

Very long answer is in this thread: https://github.com/perfect-things/perfect-home/issues/37

Lastly, I'm surprised to hear that you actually find screenshots more usable than e.g. logos or text...
I tried using screenshots several times (in extensions or other browsers like Vivaldi, Opera) and could never get used to them. A lot of the pages look similar to each other, and when minimised to a thumbnail look indistinguishable at first sight.

**Comment by h45h3ncryp73d** [comment]
Thank you for a fast reply. I get your point and just for everyone interested in the same thing as me there is a semi-automatic way to solve this by using [pageres-cli](https://github.com/sindresorhus/pageres-cli). Of course there are several Win based solutions but pageres-cli provides better automation options. But it's a linux based solution ...

While I'm at it another thing ... Would it be possible to change folder icons? Thanks.

**Comment by tborychowski** [comment]
> While I'm at it another thing ... Would it be possible to change folder icons? Thanks.

Ha, I haven't thought about an easy way, due to the complexities of the current solution...
So the initial idea was that the folder colour will match text colour selected by the user (which doesn't seem to work anymore).
I'll add that to my todo list.

You can still use **Custom CSS** to do that now, if you want.
But you either need a URL to the image (that is accessible from the PerfectHome) or convert the image to DataURI (e.g. using [this tool](https://onlineimagetools.com/convert-image-to-data-uri)).
Than the css is:
```css
.bookmarks .item-folder .item-thumb {
    mask: none;
    background: url("YOUR DATAURI") center no-repeat;
    background-size: contain;
}
``` 

For example:
```css
.bookmarks .item-folder .item-thumb {
    mask: none;
    background: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABAAAAAQACAYAAAB/HSuDAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAABmJLR0QA/wD/AP+gvaeTAAAAB3RJTUUH4QgJBwETxF4A1gAAJtVJREFUeNrt3Wmw5XV95/HP75xz96X3hYZuGkGgGQYVuxtQrOi44BI1qSgJSrTKiZQ1mRmtOM7ETGZKJ5VMZcZMTUwlGU0JiJECo9GMgrQikLiAQseIIt0tLihqqSjIyNLd957fPLi4RKSXy13O+Z/Xq4rigT769G2qv+/+/89JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACA3lNMQK+o70k7P8zatLMmJdNpZXLuf8h4akYsBAtsKLvKhbnPEAAAAgAs7IFfU3JJTkjJGSk5MckJSbY+/O9NSVZaCZbUjenkuSIAAIAAAI/t4L8kW1Py1CTnpORJqTk9ybRlQAQAAEAAoJ8P/ndkU1p5bpLnpOTcJMdaBUQAAAAEAJpw9F+cM9PKS5I8L8kT/EyBCAAAgABAU47+y3J6uvmNJOcnebxFQAQAAEAAoClH/yUZTfLClFyU5FkWgcbanaE8u7w895gCAEAAYLAO/8cneV1KLowP8INB4UkAAAABgIE5/C/Nk1Py2tS8LEnbIjBwPAkAACAA0OjD/5I8PSV/kORca8DA8yQAAIAAQAMP/7NT8p+T/LI1gJ/hSQAAAAGARhz+F2dz2vnD1Fzo5wEQAQAABACadvhflonM5g0p+U9JRi0CiAAAAAIATTv+L82Lkvx5kuOsARwFnwkAACAA0BeH/2VZn5q3pOY3rQHMkycBAAAEAHr6+L805yf5yySrrQE8Rp4EAAAQAOi5w/8dmUo7b0lykTWABeRJAAAAAYCeOf7fmZ2puTzJidYAFoEnAQAA+kjLBA09/i/NK1Jzg+MfWETnZCbX1XdnlSkAAHqfJwCadvi/NSNZkT9LzautASwRrwMAAAgALOnx/1fZkE7+LiVnWQNYYl4HAAAQAFiS4/9dOSmzuTrJ460BLBNPAgAA9DCfAdCE4/+SPD2z+YzjH1hmT87BXFX/OtOmAADoPZ4A6Pfj/9K8IMl7k4xaA+gRngQAAOhBngDo7+P//CTvd/wDPebJOZiP+nYAAAABgIU4/t+ZVya5PMmQNYAejQBeBwAA6CFeAejP4/8lqbkiSdsaQI/zOgAAgADAPI//F6fmb+Jv/gERAAAAAaChx/+leU6S/5tkxBpAn7kxnTy3XJj7TAEAIABwqOP/spyebj6RZIU1gD7lSQAAAAGAQx7/78imtHNTks3WAEQAAADmw7cA9P7xP5V2Puz4BxrCtwMAAAgAPOL4rylp5+IkZ1gDaJBzMpPr6ruzyhQAAAIASXJZ3pjkJYYAGujJOZiPigAAAEvHZwD0qHppnplkV5K2NYAG85kAAAACwAAf/5dlfbq5NckGawAiAAAAC8ErAL12/NeUdHOx4x8YIF4HAAAQAAbQpXltkhcYAhABAABYSF4B6CH14pyWVnYnGbUGMKBuTCfPLRfmPlMAACwsTwD0yvH/prTSytsc/8CA8xWBAAACQMMdn99Ocq4hALwOAACwGLwC0APqZdmSbr6QZMoaAD/hdQAAgAXkCYBe0M2fOP4BHsHrAAAAC8gTAMusXpqnJvm4XwuAR7U7Q3l2eXnuMQUAwPx5AmA5j/83pZXkfzv+AQ7JZwIAAAgAfW5rXplkuyEAjigCXFX/OtOmAACYH3/zvEzq2zKUkexNcoI1AI6Y1wEAAObJEwDLZTSvdvwDHDWvAwAAzJMnAJZBvSSjKflSkuOsATAvngQAADhKngBYntVf5fgHeEx8JgAAwFHyBMASq29KK1uzN8lJ1gB4zDwJAABwhDwBsNS25lcd/wALxmcCAAAIAD2q5HeMALDgEcDrAAAAhz1HWTL1nTkjNZ+zBMCi8DoAAMAheAJgSQtAXmMEgEXjdQAAgEPwBMBS3f6XZSLdfCvxiCrAIvMkAADAL+AJgKUym193/AMsCZ8JAAAgACzr0i83AsCSOSczuc7rAAAAP+UVgCVQL8nGlNyVpG0NgCXldQAAgId5AmBpVn6J4x9gWfhgQAAAAWAJ1bzUCADLGgF8JgAAMPC8ArDYt/+7syoH890kHWsALCuvAwAAA80TAIttJs9x/AP0BK8DAAACAIuom+cZAUAEAAAQABqs1pSUnGcJgJ6LAD4TAAAQAFhAl+aUJBsNAdBzzslMrvMkAAAgALAwSp5qBICe5XUAAEAAYMEIAAAiAACAANB4JU8xAkBfRACfCQAADMCJyqKo78hU2vmhjQH6xu4M5dnl5bnHFABAE3kCYLG0c4bjH6CveB0AABAAmJczTAAgAgAACAACAAAiAACAANAAp5gAoK8jgA8GBAAEAI7ICSYA6GvnZCbXeRIAABAAeFT1+nSSHGcJgL7ndQAAQADgEL6RzUk6hgAQAQAABIAm62azEQAaFwF8JgAAIADwCOtMANA4PhMAABAAeIQ1JgBoJK8DAAACAD+jZK0RAEQAAAABoOmqPxQCDEAE8JkAAIAAQMZMANB4PhMAABAAyIgJAAaC1wEAAAFgwA2bAEAEAAAQAAQAAEQAAIAl1THBIihpp5rhkIaGfvrP8FDS6SSddtL+mX9a5eE9W0kpNgN6PwIkP6ifMQTAQKo1qd25K6Bbu5ntzqTbfSjp3p/Z7n2Zrd9J7X4ptXtrWrk593znH8v5OWA4BACao9VKxkaT0dFkZCQZHZn7t4MeAIAmKSUp7bk/5LbSTiftzH022Iokm5KcmuSXfvL/n1qZ+vED9+fgzDfTnbkts90bcqB9eXnht+42Jov2Y2qChVffmfek5qWDefC3k8nxZHw8GRtLxkb8mAEAwBEdEjXZf+D+HDywLzOz12am/Hl5wbfvNAwCgADQO8ZGk4mJZHIyGfcNiAAAsHBBYP8Ps//Ap3Nw9uLy/O9caRQEAAFg6Y2MJNNTyYrpZNhnHgIAwKI7ODOThx66LTMH3l7O++5fGAQBQABYPJ12smJFsmqlox8AAJbTgQP78+BDu1IOvKE86+59BuGITjoTcFgT48nKlcnU1E8/mR8AAFg+w8MjGR5+Ubr1RfW68TtzcP//Kud9562G4VBcc4ugEU8AlMy90792zdyH+QEAAL1t//4H88BD78rwyGvLM772kEH4eS0T8M9/IkqyelVy0onJ5uMc/wAA0C9GRsayasVFGen8v/rRTVfWq1dPGwUBgEcqZe79/hMfl2zckAwN2QQAAPpRp9PJiunzs2LVD+q1x/ytEIAAwE9NTycnPS459hiHPwAANMXQUDvTK341K1bfXa/d+BaDIAAMsrHRZOuW5LhNDn8AAGhsCOgMZXrl6+s/bL2nXr3h1w0iADBQv+rtZNPGZOvWZHzcHgAAMAhGR1dm7aor6nWbb6sfWL3ZIAIATTc1mZx0wtzX+vkOCAAAGDyTE6dlw+qveS1AAKCpOp1k87Fzn+zf6dgDAAAGWbvTyvTK19frt9xVr159mkEEAJpiYiJ53NZkasoWAADAz9wK48dm9ZrP149sfLMxBAD6WSlzX+l3/GZ/6w8AADzKVdhuZeXK/1o/tvmL9YOb1hpEAKDfDA0lJxyfrF5lCwAA4PCmJrZl5cjX69Vrf8kYAgD9YnIiOXFrMjpqCwAA4MiNjIxl9arr6zUbfs8YAgC9bu2aZPPmua/6AwAAOOorsV2yetUf1o9uusYYAgA9qSTHbEzWr/P1fgAAwGO3Yvq8ev3mL9UPbho3hgBAz/wqtpItxyWrVtoCAABYOBMTJ2XF0DfqB1ZvNoYAwHLrdOY+7G9ywhYAAMDCGx1bnbUr99UPbTjdGAIAy2VoKNm6JRkZsQUAALB4hodHs2pyd71qw1nGEABYjuP/+C3J8LAtAACApbhBhrNy6hP1IxueaQwBgKUyPDT32P/wkC0AAIAljACdTiYmd9UPrjvXGAIAi63TSbZsmfs3AADAkkeAoXZWr7iuXr3uScYQAFi04789986/v/kHAACWNQJ0hrJi+iYfDCgAsCi/Uq1k82bv/AMAAD0SAYaGs3L803XXhvXGEABYSMduSsZG7QAAAPSO4ZHxjI5+vr4n/qZSAGBBbNyQTE3aAQAA6D1jY+uzZvNnDSEA8FitXjX3DwAAQK+amjitXnPM5YYQAJivsbHE6zQAAEA/WDV9Qd21/t8YQgDgaHU6yeZjk1JsAQAA9L5SkunpP/P1gAIAR+u4TXMRAAAAoF+0O61MTnysXh/HjADAEVm3NhkftwMAANB/RkdXZWbThwwhAHD43yzJ2jV2AAAA+tf01Hl114ZXGUIA4FF/NVpzj/577x8AAOhnpSSTk39Zd/lUcwGAX2z9umR42A4AAED/GxoaztDQVYYQAPh5Y2PJ6lV2AAAAmmNicnu9ZsOrDSEA8GOlJJs22gEAAGjYrZNkYuKt9YObfMq5AECSZM3qZGTEDgAAQPOMDI9mLFcaQgCg0/Gp/wAAQLNNTb6gXrXuiYYQAAbbhnVzn/4PAADQVKVVMjZyhSEEgME1OppMr7ADAADQfBOTp9QPb7jAEALAYFq/bu5DMQAAAJquJBkb/VNDCACDZ3wsmZywAwAAMEh30Lq6a8O/M4QAMFjWr7MBAAAweMbG3mwEAWBwTIwn474GEwAAGECjo6s8BSAADA5f+wcAAAx2BPh9IwgAzTcykkx49x8AABhgY2Pr61UbXmwIAaDZ1q62AQAAwNjQ/zCCANBcnXYyNW0HAACA8YmT67VrTzaEANBMK1ckrWIHAACAVkky7CkAAaCpAWClDQAAAH5sdOx5tbpLBYCmGR9PhoftAAAA8GPDQ8P5yPrXGEIAaJaVK2wAAADw84aG/70RBIAGrVySqSk7AAAA/LzxsZPr9esmDSEANMPERNI2NQAAwCOv0nbJgfbrDSEANMO0r/4DAAB4VMNDv2kEAaABSjLpaRYAAIBHNTb6uHr91lFDCAD9bXzM4/8AAACHvEzbJQ898EpDCAD9bWrCBgAAAIczNHShEQSA/ubxfwAAgMMbHT7TCAJA/+q0k5EROwAAABzO0Mh4ff/6Ew0hAPSnsXEbAAAAHImSZKL1CkMIAP1pfMwGAAAAR3yhtp9jBAFAAAAAAGi64aFtRhAA+lBJRn2NJQAAwJEHgJEV9T0ZNoQA0F9GhpNS7AAAAHDEF2pJptY9yxACQH8Z9en/AAAAR3+ltp5tBAFAAAAAAGi6dme7EQSA/jIsAAAAABy1ofaJRhAA+iwADNkAAADgaLU7K40gAPSXIQEAAADg6G+pjq9TEwD66gd2JC3TAgAAHLXSKvX9670GIAD0ieGRCSMAAADM02jOMYIA0B+GhjyyAgAAMO9LteUJAAGgT3Taw0YAAACYp1KOMYIA0B/aAgAAAMBjCAAbjCAA9Mmq7REjAAAAzPemKuuMIAD0h3arYwQAAIB5qsUHqwsA/aLYFQAAYN6XavFatQDQL/e/AAAAAPAYeKpaAOibVe0KAAAwX8UTAAJA//y02hUAAGDeJ5UnAAQAAAAAQAAAAAAABAAAAAAQAAAAAAABAAAAABAAAAAAAAEAAAAAEAAAAAAAAQAAAAAQAAAAAAABAAAAABAAAAAAQAAAAAAABAAAAABAAAAAAAAEAAAAAEAAAAAAAAQAAAAAQAAAAAAABAAAAAAQAAAAAAABAAAAABAAAAAAAAEAAAAAEAAAAAAAAQAAAAAQAAAAAAABAAAAAAQAAAAAQAAAAAAABAAAAABAAAAAAAAEAAAAAEAAAAAAAAQAAAAAQAAAAAAABAAAAAAQAAAAAAABAAAAABAAAAAAAAEAAAAAEAAAAAAAAQAAAAAQAAAAAAABAAAAAAQAAAAAQAAAAAAABAAAAABAAAAAAAAEAAAAAEAAAAAAAAQAAAAAQAAAAAAAAQAAAAAQAAAAAAABAAAAABAAAAAAAAEAAAAAEAAAAAAAAQAAAAAQAAAAAEAAMAEAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAANBr2u3vGwEAAMBNJQA03ejoPiMAAAC4qQQAAAAAQAAAAAAABAAAAABAAAAAAAAEAAAAABAAAAAAAAEAAAAAEAAAAAAAAQAAAAAQAAAAAAABAAAAABAAAAAAAAEAAAAABAAAAABAAAAAAAAEAAAAAEAAAAAAAAQAAAAAQAAAAAAABAAAAABAAAAAAAAEAAAAABAAAAAAAAEAAAAAEAAAAAAAAQAAAAAQAAAAAAABAAAAABAAAAAAAAEAAAAABAAAAABAAAAAAAAEAAAAAEAAAAAAAAQAAAAAQAAAAAAABAAAAABAAAAAAAABAAAAABAAAAAAAAEAAAAAEAAAAAAAAQAAAAAQAAAAAAABAAAAABAAAAAAAAEAAAAABAAAAABAAAAAAAAEAAAAAEAAAAAAAAQAAAAAQAAAAAAABAAAAABAAAAAAAABAAAAABAAAAAAAAEAAAAAEAAAAAAAAQAAAAAQAAAAAAABAAAAABAAAAAAQAAAAAAABAAAAABAAAAAAAAEAAAAAEAAAAAAAAQAAAAAQAAAAAAABAAAAABAAAAAAAABAAAAABAAAAAAAAEAAAAAEAAAAAAAAQAAAAAQAAAAAAABAAAAABAAAAAAQAAAAAAABAAAAABAAAAAAAAEAAAAAEAAAAAAAAQAAAAAQAAAAAAABAAAAAAQAAAAAAABAAAAABAAAAAAAAEAAAAAEAAAAAAAAQAAAAAQAAAAAAABAAAAABAAAAAAQAAAAAAABAAAAABAAAAAAAAEAAAAAEAAAAAAAAQAAAAAQAAAAAAABAAAAAAQAAAAAAABAAAAABAAAAAAAAEAAAAAEAAAAAAAAQAAAAAQAAAAAAABAAAAAAQAAAAAQAAAAAAABAAAAABAAAAAAAAEAAAAAEAAAAAAAAQAAAAAQAAAAAAABAAAAAAQAAAAAAABAAAAABAAAAAAAAEAAAAAEAAAAAAAAQAAAAAQAAAAAAABAAAAAAQAAAAAQAAAAAAABAAAAABAAAAAAAAEAAAAAEAAAAAAAAQAAAAAQAAAAAAAAQAAAAAQAAAAAAABAAAAABAAAAAAAAEAAAAAEAAAAAAAAQAAAAAQAAAAAAABAAAAAAQAAAAAQAAAAAAABAAAAABAAAAAAAAEAAAAAEAAAAAAAAQAAAAAQAAAAAAAAQAAAAAQAAAAAAABAAAAABAAAAAAAAEAAAAAEAAAAAAAAQAAAAAQAAAAAEAAAAAAAAQAAAAAQAAAAAAABAAAAABAAAAAAAAEAAAAAEAAAAAAAAQAAAAAEABMAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAAAgAAAAAgAAAAAAACAElS66wRAAAA3FQCQNOVHDACAADAvO03gQDQH2oVAAAAAAQAAaD5ih9WAACAeZ9UAoAA0D8eNAEAAMB8VTeVANA3fmACAACAeeq2vm8EAaBf3G0CAACA+V6qXTeVANA31CoAAAA3lQDQfEWtAgAAmPdJVQUAAaBPzNavGwEAAGCeusN3GkEA6A8PbbwryYwhAAAAjtrBfO0L3zKDANAXyjNumElylyUAAACOUs2d5fzMGkIA6KMKkK8aAQAAwC0lADRdrbcbAQAA4KgLwBdtIAD0WQDI540AAADglhIAGq98zgYAAABHe6XOCgACQJ8ZHb41SdcQAAAAR6yb4dHbzCAA9JXyhFvvT7LPEgAAAEdsz8O3FAJAv1WA+kkjAAAAHKGajxtBAOjXH14BAAAA4Igv1OKGEgD6NQD44QUAADhys26oRVRMsIj3f03Jzad+M8kx1gAAADjkBfWNsnPvFjssHk8ALKJSUpPssgQAAMBhL6hrbCAA9Ln6YRsAAAAc7nQqbicBoM/tH/5okhlDAAAAPKqDae+/zgwCQF8rT/v8PYlvAwAAAHh09R/K9q/80A4CQBN+mK+0AQAAwKOdTK0rjCAANENn9r3xGgAAAMAvcjCp7zeDANAI5cw7vpfkBksAAAA84mK6tpy15/t2EACa5N0mAAAA+Hndy20gADTLzI+uTOq9hgAAAPixem9ak39rBwGgUcpT7nowibIFAADwk0OpvKts3/2AIQSA5unmbUYAAAB4WG1fbAQBoJHK2XtvTfJJSwAAANSPl523/ZMdBIAG/4yXPzECAABA+Z82WOLFTbDE939NK7ds+0Jq3WYNAABgQO3Njj2nlZKuKZaOJwCWWCnpptt9qyUAAICBVctbHP8CwGBYPXtJUr9hCAAAYAB9PasPvssMAsBAKI+/Y39q/sgSAADAwKnlv5XH37HfEALA4GhPviPJVwwBAAAMzvGfO/LAhncaQgAYKGX77oOp5c2WAAAABucQqm8qz7hhxhDLNL8Jlk+taeXmbTcmdac1AACAhrspO/Y8pZRUUywPTwAso1LSTa2vS/wGAAAAGq2m1Xqd418AGOwIcNaeG1NzhSUAAIAGu6xs/+KnzSAAMNt9Q5L7DAEAADRPvTet8kY7CAAkKU/Z982k/q4lAACA5t3/rTeU7bd/2xA9cHuaoEd+T9S0cvMpNyTladYAAAAa4u+zY88zvPvfGzwB0CNKSTetelGSB60BAAA0wAOpucjxLwDwiyLA9n17UvIfLQEAAPT/gZPfKWft2WeIXvoloafUmpKbT/27JC+0BgAA0KeHzdXZufeX/e1/b/EEQI8pJTUHD/5Wku9YAwAA6EPfSru+0vEvAHAkEeCpX/5uuvWCJDPWAAAA+shMkpeV7fvuNoUAwJFGgLP3Xp9Sf88SAABA/6j/oezc8/d26NE70wQ9/FunpuTmbVck9XxrAAAAPe6KsnPPBWboXZ4A6GGlpGai9a+TfNYaAABA7x4v2Z2R4d8yRK//MtHz6i3bjkm33pRkizUAAIAe8810Z84uZ99xlyl6mycA+kDZfvu3k9bzk3qvNQAAgB5yX7r1+Y5/AYCFjAA7v3hbSuulSfZbAwAA6AEPpuTF5ey9t5pCAGChI8CO269N6q8kOWANAABgGR1Mzfllx54bTCEAsFgRYOfea1Lyssx9vyYAAMBSm00pryhn7fmQKQQAFjsC7NjzvpTyqiSz1gAAAJbQTFJfWXbcfoUp+vCWNEH/qjef8qLU8p4kI9YAAAAW2YGUvKzs2PM+UwgALEsEOPl5qa33JRmzBgAAsEgeSOqvlZ17rzGFAMByRoBbTj433dYHkqyxBgAAsMDuTvLisnPPp0whANATEeCkE9PtXJ3kZGsAAAALdDJ+OaX7grJj715b9D8fAtiU35bb7/hyOjPnJrnRGgAAwAL4ZFqzZzv+BQB6MQKcecf3smrmGUneag0AAOAxeHsm2v+qbN93tykadDOaoJnqZ065MClvSzJuDQAA4Ag9lFJ/u+zYe7EpBAD6KQLcdOqT08rl8bkAAADA4e1J2heUnbf9kymaySsADVbO3rM7Mz96YrwSAAAAHEqt78rI8HbHf8NvRBMMyO/nm0/9tdT8nyRrrQEAADzse6nlonLW7R8wRfN5AmBAlB173pf9Qycnebs1AACAlPI36cz8C8f/AP2Sm2Dw1Ju3PT/d+hcpOd4aAAAwcL6abl5Tzt7zEVMMFk8ADKCy4/ar0544LbX8bmp+ZBEAABgID6TUP85E+wzH/4DegiYYbPVTJx+bdvnvKeVCPw8AANBYH0qn/Nty5u13mkIAYNBDwE2nnJF26/dT60utAQAAjXFtan1jOWvvLaZAAOCfh4BbTj433dYfJHm6NQAAoG//ZP+x1PJfyll7brQFAgCHCQHbzsxs93Up5YIkHYsAAEDP6ya5OjV/5PBHAGAeIeCkE1M7r03NK5KssAgAAPTcn9rvTcplKd0/LTv2fcUeCAA8tv+kXL91NOMjL0wpFyV5pp8dAABY9mtud5K3Z3j43eUJt95vEAQAFj4G3HLyqZlt/UZa5fzUus0iAACwZL6Y5MqUemXZsXevORAAWLoYcNMpZ6SVl6SU56fmSUlaVgEAgAXTTbI7yYfTynvL9j2fNwkCAD0QA07fkDJ7Xkp9TpKnJdliFQAAONo/WOfOlPLxpLsrB2c+Up765e8aBQGA3v7v1mdO35w6c25aOSe1PjHJv0zKSssAAMBP/tR8b1JuTcnnkvKpzB78RDn7jrvsggBA///n7R+3HZ+DOT2le1JSHpfkhIf/2ZhkrYUAAGjaH4GTfD/Jt5N8NSlfTbpfTWl9KaX1hbL9tq+bCAGAwfsvY00rnz1pTbqtNZlpTaRdVj38P4yl1lELAQDQu5dVeSilPJgkma33pNO9P63u9/OkO+4uJdVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/GL/Hz1QIjhOZ3b2AAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDE3LTA4LTA5VDA3OjAxOjE4KzAwOjAwpo5RSwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAxNy0wOC0wOVQwNzowMToxOCswMDowMNfT6fcAAAAASUVORK5CYII=") center no-repeat;
    background-size: contain;
}
```
