### ISSUE TITLE
Home shortcuts should be in the middle, top to bottom

### ISSUE THREAD

**Issue by Apofen** [perfect-things/perfect-home#149]
Default margin is set to top  just below the title. If you have smaller set of shortcuts and Firefox is in expanded to full page it doesn't look good while icons are at the top.

**Comment by tborychowski** [comment]
No, they shouldn't. They are exactly where I wanted them to be.
Now, you could style your homepage to do what you want.
E.g. you could paste the code below to the `Customize`/`Custom CSS` section in the sidebar settings:

```css
#app {
  align-items: center;
  justify-content: center;
  flex-flow: column;
  height: 100%;
}
```
Assuming no additional (and conflicting) changes - the code above would center your grid horizontally and vertically).
