### ISSUE TITLE
Possible to change folder title color using a variable?

### ISSUE THREAD

**Issue by kleshas** [perfect-things/perfect-home#152]
> Hi, still using this fantastic package after all these years.  Revisiting the css -  how to change the titles of each column (eg Perfect Home, TODO, Bookmarks Menu... in your comment on Jul 20, 2021 in this thread).  Mine stay white.  I guess I'm looking for a color-title: var(--color3); type of entry to put in .folder

_Originally posted by @kleshas in https://github.com/perfect-things/perfect-home/issues/134#issuecomment-1804919452_

**Comment by tborychowski** [comment]
Hi, thanks for using the app :-)

The easiest thing is to right-click it and select "Inspect" from the context menu. Then you look for patterns in `class` attribute and e.g.:
![2023-11-10 at 09 03 40](https://github.com/perfect-things/perfect-home/assets/392513/8b206b31-993f-403b-8fcf-832232dfce60)

so to change the colour of the button text, you can use:
```css
.folder-title { color: var(--color3); }
```

note: sometimes there are more styles and in css "specificity" (which selector is more important than others) plays a role, so to ensure your styling "wins", you can make it more "specific", e.g. by adding class names from the button parent divs, like so:
```css
.folders .folder .folder-header .folder-title { 
   color: var(--color3); 
}
```
