### ISSUE TITLE
Add option to set custom backgound (wallpaper)

### ISSUE THREAD

**Issue by sbstn87** [perfect-things/perfect-home#63]
Could you please add an option to set a custom image in the background?

**Comment by tborychowski** [comment]
but you can already do this :-)
just open settings and in the "Custom CSS" field paste the below snippet:

```css
body {
    background: url('https://source.unsplash.com/weekly?fire') center/cover no-repeat
}
````
